

class RandomGenerator{
	constructor(min, max){ 
		this.min = min;
		this.max = max;
		this.random = null;
		if(min===undefined){
			this.min = 1;
		}
		if(max === undefined){
			this.max = 10;
		}
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		var range = this.max - this.min + 1;
		var randomPercent = Math.random();
		var percentofRange = randomPercent * range;
		var wholeNumber = Math.floor( percentofRange );
		this.random = wholeNumber;
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		return {
			'min' : this.min, 'max': this.max
		}
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.random;
	}
}